- name: Firewall changes
  hosts: web_servers
  become: true

  tasks:
    - name: Enable a service in the firewalld
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled

    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded